# Uncomment the next line to define a global platform for your project
# platform :ios, '0.0'

target 'ReactiveReactivity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveReactivity 
    
    pod 'RxCocoa'
    pod 'RxSwift'
	
    pod 'Giphy'
    
end
