# Uncomment the next line to define a global platform for your project
# platform :ios, '22.0'

target 'RxGraphicsInterFi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxGraphicsInterFi

    pod 'RxCocoa'
    pod 'RxSwift'

end
