# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RxSplash' do
  
  use_frameworks!

  pod 'UnsplashPhotoPicker', '~> 1.1.1'

end
